# Generated by Django 3.0.5 on 2020-06-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200602_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiod',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='activity_periods',
            field=models.ManyToManyField(to='webapp.ActivityPeriod'),
        ),
    ]
